---
- name: Playbook to purge ovirt-engine backup older than 30 days 
  hosts: all
  tasks:
    - name: Run `rm` command on files more than 30 days old 
      shell: find /root/rhv-engine-backup/engine.backup/rhv-engine-backup-{{ item }}/*/root -mtime +30  -exec rm -f {} \;
      with_items: "{{rhv_manager_hostnames}}"



