---
- name: Playbook to purge ovirt-engine backup older than 30 days 
  hosts: all
  tasks:
    - name: Run `rm` command on files more than 30 days old 
      command: find /root/rhv-engine-backup/engine.backup/"{{ rhv_manager_fqdn }}"/root -mtime +30  -exec rm -f {} \;



